spring.application.name=furniture-backend

# =========================
# DATABASE (NEON CLOUD POSTGRESQL)
# =========================
spring.datasource.url=jdbc:postgresql://ep-blue-dew-aos89zsa.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WPS5pUJfo6xu
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SERVER CONFIG (IMPORTANT FOR DEPLOYMENT)
# =========================
server.port=${PORT:8080}

# =========================
# JWT CONFIG
# =========================
jwt.secret=MySuperSecretKeyForFurnitureProject2026